### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by sebhtml**

### CODE REVIEW

**Comment by sebhtml** [comment]
This will close

https://github.com/kbase/assembly/issues/244

**Comment by levinas** [comment]
Awesome. One question about memory usage:

I'm not sure how the memory option is being interpreted by megahit. Is it mindful of what the available memory is? I wonder if we need to cap the memory at:

system_memory / total_threads * process_threads_allowed

**Comment by sebhtml** [comment]
I added the requested change.

**Comment by sebhtml** [comment]
I ran into this problem BTW: I expected self.process_threads_allowed to be an integer (int). However it is a string. I was multiplying a string and it took me some time to figure this out.

**Comment by levinas** [comment]
I'll run a manual test by replacing all the a6 assembler with megahit in arast.t.

**Comment by sebhtml** [comment]
OK. let me know all it goes.

**Pull request merged**
